name: psort
channels:
  - defaults
  - conda-forge  # conda-forge channel
dependencies:
  - python=3.10.13
  - numpy=1.26.3
  - matplotlib=3.8.0
  - scikit-learn=1.3.0
  - decorator=5.1.1
  - pytables=3.9.2
  - pyqt=5.15.10
  - pyqtgraph=0.13.1
  - numba=0.58.1
  - umap-learn=0.5.3
  - python-neo=0.12.0  # conda-forge channel
